# GET https://ps1325.cs01.cloudinsights.netapp.com/rest/v1/cloudsecure/activities HTTP/1.1
# 	?limit=10
# x-cloudinsights-apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJjcmVhdG9yTG9naW4iOiJzYW1scHxOZXRBcHBTQU1MfG15dWljaGkiLCJkaXNwbGF5TmFtZSI6Im15dWljaGkgdGVzdCAob24gYmVoYWxmIG9mIFl1aWNoaSBNYXNoaW1vKSIsInJvbGVzIjpbXSwiaXNzIjoib2NpIiwibmFtZSI6Im15dWljaGkgdGVzdCIsImFwaSI6InRydWUiLCJleHAiOjE2NTQ3NjgzMTMsImxvZ2luIjoiNGU5NDQwNmUtMWViZi00ZDA5LTkyMDQtNGExYzZkNzM5NmI3IiwiaWF0IjoxNjIzMjMyMzEzLCJ0ZW5hbnQiOiIwZjAzM2NmMC1jZDNlLTQ2N2YtYjY2Mi0yODRlNTRkNWJmYTQifQ.VCpeD8LRJrrkLI83DVGjHS44kWSdPqxoF1uPlWOKF4jcu4jHgIiH993ietfcStrd

GET https://ps1325.cs01.cloudinsights.netapp.com/rest/v1/cloudsecure/activities
	?limit=10
	&deviceName=svm-shita01
	# &fromTime=1623078000000
	&fromTime=1623164400000
	&toTime=1623250800000
# Content-Type: application/json
x-cloudinsights-apikey: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzM4NCJ9.eyJjcmVhdG9yTG9naW4iOiJzYW1scHxOZXRBcHBTQU1MfG15dWljaGkiLCJkaXNwbGF5TmFtZSI6Im15dWljaGkgdGVzdCAob24gYmVoYWxmIG9mIFl1aWNoaSBNYXNoaW1vKSIsInJvbGVzIjpbXSwiaXNzIjoib2NpIiwibmFtZSI6Im15dWljaGkgdGVzdCIsImFwaSI6InRydWUiLCJleHAiOjE2NTQ3NjgzMTMsImxvZ2luIjoiNGU5NDQwNmUtMWViZi00ZDA5LTkyMDQtNGExYzZkNzM5NmI3IiwiaWF0IjoxNjIzMjMyMzEzLCJ0ZW5hbnQiOiIwZjAzM2NmMC1jZDNlLTQ2N2YtYjY2Mi0yODRlNTRkNWJmYTQifQ.VCpeD8LRJrrkLI83DVGjHS44kWSdPqxoF1uPlWOKF4jcu4jHgIiH993ietfcStrd